tasks:
  process_invoices_task:
    description: |
      Automatically process invoices from suppliers using the n8n-invoice-automation workflow pattern:
      
      1. GMAIL RETRIEVAL: Check Business's designated email for new invoices (PDF attachments)
      2. PDF PROCESSING: Extract text from invoice PDFs using OCR technology
      3. AI DATA PARSING: Use AI to convert raw text into structured JSON with:
         - Invoice summary (supplier, amount, date, invoice number)
         - Detailed line items with Business categorization
         - Malaysian supplier identification and special handling
      4. GOOGLE SHEETS INTEGRATION: Save data to two sheets:
         - "Invoices" tab: Summary information
         - "Invoice_Items" tab: Line-item details
      5. ARCHIVAL: Save PDF to Google Drive with proper naming convention
      6. EMAIL LABELING: Mark processed emails with "business-processed" label
      
      Special focus on Malaysian suppliers and child nutrition product categories.
      
      Context: {email_context}
      Processing Limit: {invoice_limit}
    expected_output: |
      Complete invoice processing report including:
      - Number of invoices processed from Gmail
      - Detailed extraction results for each invoice (supplier, amount, categories)
      - Google Sheets update confirmation with row counts
      - Google Drive archival status with file locations
      - Malaysian supplier special processing notes
      - Any errors or items requiring human review
      - Business expense categorization summary (ingredients, marketing, operations, etc.)
    agent: financial_document_processor
    
  organize_documents_task:
    description: |
      Organize and archive company documents using AI-powered content analysis following the 
      Custodian project pattern:
      
      1. DOCUMENT SCANNING: Analyze files in specified folders (Google Drive, local storage)
      2. CONTENT EXTRACTION: Use OCR for images/PDFs, read text from documents
      3. AI CATEGORIZATION: Determine document category with Business-specific categories:
         - Child nutrition research and studies
         - Malaysian market analysis and insights
         - Supplier contracts and agreements
         - Product development documentation
         - Regulatory compliance files
         - Marketing materials and brand guidelines
      4. INTELLIGENT NAMING: Generate descriptive filenames following Business conventions
      5. AUTOMATED FILING: Move files to appropriate folders with proper structure
      
      High-confidence documents are automatically processed; low-confidence files are flagged for review.
      
      Input: {document_folders}
      Categories: Child nutrition, Malaysian market, suppliers, product development, compliance, marketing
    expected_output: |
      Comprehensive document organization report including:
      - Total documents processed and categorized
      - Category breakdown with file counts
      - Successfully renamed and moved files list
      - Files requiring human review (low confidence categorization)
      - Folder structure optimization recommendations
      - Business-specific document insights (nutrition research trends, supplier patterns, etc.)
      - Archive completion status with organized folder structure
    agent: digital_archivist
    
  prepare_meeting_brief_task:
    description: |
      Prepare comprehensive meeting briefings following the prep-for-a-meeting crew pattern:
      
      1. CALENDAR ANALYSIS: Review upcoming meeting details from calendar
      2. TOPIC RESEARCH: Conduct focused research on meeting topics with emphasis on:
         - Child nutrition industry trends
         - Malaysian market developments
         - Competitor analysis in natural products space
         - Regulatory updates affecting family nutrition products
      3. PARTICIPANT RESEARCH: Analyze meeting participants' backgrounds and Business interaction history
      4. INTERNAL DOCUMENT REVIEW: Search Google Drive for relevant Business documents:
         - Previous meeting minutes on similar topics
         - Research reports and market analysis
         - Product development updates
         - Supplier relationship documents
      5. BRIEFING COMPILATION: Create structured brief with key insights and talking points
      
      Focus on information that supports strategic decision-making for child nutrition mission.
      
      Input: {meeting_details}
      Research Focus: Child nutrition trends, Malaysian market, natural products industry
    expected_output: |
      Complete meeting preparation brief including:
      - Meeting overview and objectives summary
      - Key industry trends relevant to discussion (child nutrition focus)
      - Participant profiles and Business relationship context
      - Relevant internal documents summary with key excerpts
      - Malaysian market context and cultural considerations
      - Recommended talking points and strategic questions
      - Potential decisions points and follow-up actions
      - Supporting data and research findings
      - Risk factors and opportunities identification
    agent: meeting_assistant
    
  analyze_business_data_task:
    description: |
      Answer natural language business questions by analyzing Excel/Google Sheets data with focus on 
      Business's markets and products:
      
      1. DATA SOURCE IDENTIFICATION: Locate relevant spreadsheets (sales, inventory, market data)
      2. QUERY PROCESSING: Interpret natural language questions into data analysis requirements
      3. DATA ANALYSIS: Perform calculations, trend analysis, and insights extraction
      4. MARKET CONTEXT: Apply Business business context to findings:
         - Child nutrition product performance
         - Singapore and Malaysian market metrics
         - Seasonal trends in family-oriented products
         - Supplier performance and cost analysis
      5. INSIGHT GENERATION: Provide actionable insights supporting business decisions
      
      Example queries:
      - "Which was our most popular product in Singapore this quarter?"
      - "How are our Malaysian supplier costs trending?"
      - "What's our market share in child nutrition products?"
      
      Input: {business_question}
      Data Sources: {data_files}
    expected_output: |
      Comprehensive business data analysis including:
      - Clear answer to the specific business question asked
      - Supporting data visualizations and charts (when applicable)
      - Trend analysis with historical context
      - Market-specific insights (Singapore/Malaysia focus)
      - Child nutrition product performance metrics
      - Comparative analysis with previous periods
      - Strategic recommendations based on findings
      - Data quality notes and limitations
      - Suggested follow-up questions or deeper analysis opportunities
    agent: data_analyst