recruitment_analysis:
  description: >
    Analyze the recruitment request and create a comprehensive 
    hiring strategy including job description, candidate requirements, 
    and evaluation criteria
  expected_output: >
    A detailed recruitment plan with job description, required 
    qualifications, interview process, and timeline
  agent: hr_specialist
  human_input: false

job_posting_creation:
  description: >
    Create compelling job postings that attract qualified candidates 
    while reflecting company culture and values
  expected_output: >
    Professional job posting ready for publication on job boards 
    and company website
  agent: hr_specialist
  human_input: false

candidate_evaluation:
  description: >
    Evaluate candidate applications against job requirements and 
    company culture fit
  expected_output: >
    Ranked list of candidates with evaluation scores and 
    recommendations for next steps
  agent: hr_specialist
  human_input: true
  approval_required: true

admin_task_processing:
  description: >
    Process administrative requests including document management, 
    financial operations, and operational coordination
  expected_output: >
    Completed administrative task with documented process and 
    quality control measures
  agent: admin_specialist
  human_input: false

financial_document_review:
  description: >
    Review and process financial documents including invoices, 
    expense reports, and budget analysis
  expected_output: >
    Processed financial documents with accuracy verification 
    and compliance confirmation
  agent: admin_specialist
  human_input: true
  approval_required: true

meeting_coordination:
  description: >
    Coordinate meetings including scheduling, preparation of materials, 
    and logistics management
  expected_output: >
    Fully organized meeting with confirmed attendees, prepared 
    materials, and logistics arranged
  agent: admin_specialist
  human_input: false

crisis_response:
  description: >
    Develop immediate response plan for crisis situations including 
    stakeholder communication and recovery timeline
  expected_output: >
    Comprehensive crisis response plan with immediate actions, 
    communication strategy, and recovery timeline
  agent: conductor
  human_input: true
  approval_required: true
  priority: high

human_approval:
  description: >
    Review and approve critical business decisions requiring 
    human oversight and management approval
  expected_output: >
    Approval decision with reasoning and any required modifications
  agent: human_reviewer
  human_input: true
  approval_required: true
